### PR TITLE
django 2 compatibility set MIDDLEWARE

### PR DESCRIPTION
**Pull request by bj00rn**

### CODE REVIEW

**Comment by bj00rn** [comment]
@RealOrangeOne django 2 uses `MIDDLEWARE` setting does it not?

**Comment by RealOrangeOne** [comment]
It does, which explains why I had to do https://github.com/dabapps/django-log-request-id/pull/33/commits/f9471914619068692186f17cfd8d471d1328fcf6. 

Not entirely sure why the tests pass without this. But as a fix this is definitely really nice!

**Comment by bj00rn** [comment]
> It does, which explains why I had to do [f947191](https://github.com/dabapps/django-log-request-id/commit/f9471914619068692186f17cfd8d471d1328fcf6).
> 
> Not entirely sure why the tests pass without this. But as a fix this is definitely really nice!

Yes, it's really strange the tests pass without `MIDDLEWARE` being set. `MIDDLEWARE_CLASSES` is deprecated since 1.10 https://docs.djangoproject.com/en/1.11/ref/settings/#middleware-classes

**Comment by RealOrangeOne** [comment]
Well, the tests pass with this added, and it's more correct, so looks good to me!

**Pull request merged**
