### PR TITLE
Generates Request ID when not found in header.

### PR DESCRIPTION
**Pull request by mustafashabib**
When the `REQUEST_ID_HEADER_SETTING` is set but no ID was available in the header, it would always default to `NO_REQUEST_ID`. This patch allows you to set the setting `GENERATE_REQUEST_ID_IF_NOT_IN_HEADER_SETTING` to `True` and the request_id will be generated instead.

:pray: you accept this 

Tests pass using python35 -- 

~~~shell
(dlrid)➜  django-log-request-id git:(master) tox
GLOB sdist-make: /Users/mshabib/Projects/django-log-request-id/setup.py
py35 inst-nodeps: /Users/mshabib/Projects/django-log-request-id/.tox/dist/django-log-request-id-1.1.0.zip
py35 installed: Django==1.9.1,django-log-request-id==1.1.0,requests==2.9.1,wheel==0.26.0
py35 runtests: PYTHONHASHSEED='306653597'
py35 runtests: commands[0] | django-admin.py test
Creating test database for alias 'default'...
........
----------------------------------------------------------------------
Ran 8 tests in 0.011s

OK
Destroying test database for alias 'default'...
_______________________________________________________________ summary _______________________________________________________________
  py35: commands succeeded
  congratulations :)
~~~ 

with a slight change to how the `MIDDLEWARE_CLASSES` setting was being concatenated to `global_settings.MIDDLEWARE_CLASSES`

### CODE REVIEW

**Comment by pheuter** [comment]
_just_ ran into this myself, would be super helpful :+1:

**Comment by mustafashabib** [comment]
ping :)

**Comment by j4mie** [comment]
Hi! I'm really sorry it's taken so long for me to look at this. I've just merged another PR and this now has conflicts. If you've got time to resolve them, that'd be great - if not, I'm happy to do it myself in a separate branch.

Also, can you remove the version bump please? I'll do that myself just before releasing. Cheers!

**Comment by j4mie** [comment]
Superceded by https://github.com/dabapps/django-log-request-id/pull/15

**Pull request closed without merging**
