### PR TITLE
drop support for django < 2, add test targets for django 2

### PR DESCRIPTION
**Pull request by bj00rn**
- [x] drop django 1 support
- [x] add targets for django 2.0, 2.1

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
Support for versions < 2.0 can't be dropped until 1.11 goes EoL, which isn't until April 2020. We still want to maintain support for at least the current LTS versions.

**Comment by bj00rn** [comment]
@RealOrangeOne 👍 maybe branch off a django1 branch and do a major release?

**Comment by RealOrangeOne** [comment]
I'd rather we maintain support in the released version for all versions still supported by Django. It means those running `1.11` don't have to hunt for an unreleased version, or pin to a previous one. 

I'd definitely welcome a PR which simply adds Django 2.2 as a test target, though! And removes test targets for versions which are EoL.

**Comment by pzelnip** [comment]
1.11 is still LTS, and until that changes many orgs won't be moving to 2.x.

**Pull request closed without merging**
